apiVersion: v1
data:
  agent.yaml: |
    connections:
      "postgres":
        name: "PostgreSQL"
        postgres:
          host: localhost
          port: 54320
          username: postgres
          password: ${POSTGRES_PASSWORD}
          database: db
          allow_insecure: true
kind: ConfigMap
metadata:
  name: example-synq-dwh-agent-config
  namespace: synq
---
apiVersion: v1
data:
  POSTGRES_PASSWORD: cGFzcw==
  SYNQ_CLIENT_ID: ZXhhbXBsZS1jbGllbnQtaWQtZnJvbS1zeW5x
  SYNQ_CLIENT_SECRET: ZXhhbXBsZS1jbGllbnQtc2VjcmV0LWZyb20tc3lucQ==
kind: Secret
metadata:
  name: example-synq-dwh-agent-env
  namespace: synq
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: minor
    keel.sh/pollSchedule: '@every 5m'
    keel.sh/trigger: poll
  name: example-synq-dwh-deployment
  namespace: synq
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: synq-dwh
  template:
    metadata:
      labels:
        deployment: synq-dwh
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: example-synq-dwh-agent-env
        image: europe-docker.pkg.dev/synq-cicd-public/synq-public/synq-dwh:v0.4.0
        imagePullPolicy: Always
        name: synq-dwh-container
        volumeMounts:
        - mountPath: /opt/synq-dwh/
          name: synq-dwh-agent-config-volume
      volumes:
      - configMap:
          name: example-synq-dwh-agent-config
        name: synq-dwh-agent-config-volume
