apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: example-
configMapGenerator:
  - files:
      - agent.yaml
    name: synq-dwh-agent-config
    behavior: merge
secretGenerator:
  - envs:
      - agent.env
    name: synq-dwh-agent-env
    behavior: merge
resources:
  - ../../base
namespace: synq

patches:
  - path: patch-version.yaml

generatorOptions:
  disableNameSuffixHash: true
