name: Validate PR
"on":
  pull_request:
    branches:
    - main
    paths:
    - base/**
    - overlays/**
    - scripts/**
    - .github/workflows/validate-pr.yaml
concurrency:
  cancel-in-progress: true
  group: validate-pr-${{ github.event.pull_request.number }}
defaults:
  run:
    shell: bash
jobs:
  validate-image-version:
    name: Validate image version
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        # Ensure jq and curl are available
        command -v jq >/dev/null || sudo apt-get update && sudo apt-get install -y jq
        command -v curl >/dev/null || sudo apt-get update && sudo apt-get install -y curl
    - name: Make script executable
      run: chmod +x scripts/validate-image-version.sh
    - name: Validate image version
      run: ./scripts/validate-image-version.sh

  validate-kustomize-build:
    name: Validate Kustomize build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        overlay:
        - example
    steps:
    - uses: actions/checkout@v4
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
    - name: Validate kustomize build for ${{ matrix.overlay }}
      run: |
        chmod +x scripts/validate-kustomize-build.sh
        ./scripts/validate-kustomize-build.sh ${{ matrix.overlay }}
